### ISSUE TITLE
String literals maybe have type char? Other weird errors

### ISSUE THREAD

**Issue by Limvot** [lotusronin/neuro#2]
Here's the sample code

>extern fn printf(a : *char) : int;
>fn main() : int {
>    a : char;
>    b : *char;
>
>    va := "hi";
>    vb : *char = "hi";
>    return 0;
>}

Note that va is emitted as an i8 not an *i8

Also this weirdness:

> <Error> hello.nro:6:15
>    vb : *char = "hi";
>---------------^
>Variable Decl and Assign Type Error: Cannot assign *char to a variable of type *char

**Comment by lotusronin** [comment]
Issue fixed.
